const getWord = ()=>{
    const adjectives = [
        "apple", "airplane", "ball", "banana", "beach", "bear", "bed", "bee", "bell", "bike",
"bird", "boat", "book", "boot", "box", "bread", "broom", "bus", "cake", "camera",
"candle", "car", "carrot", "cat", "chair", "cheese", "chicken", "cloud", "coat", "couch",
"cow", "cup", "desk", "dog", "door", "duck", "eagle", "egg", "elephant", "fan",
"feather", "fish", "flag", "floor", "flower", "fork", "fox", "frog", "game", "ghost",
"gift", "giraffe", "goat", "grape", "grass", "guitar", "hammer", "hat", "hill", "horse",
"house", "ice", "island", "jacket", "jar", "jungle", "kangaroo", "key", "kite", "ladder",
"lamp", "leaf", "lemon", "lion", "lizard", "lock", "milk", "mirror", "monkey", "moon",
"mountain", "mouse", "mug", "nail", "needle", "net", "nose", "notebook", "ocean", "orange",
"owl", "panda", "pants", "paper", "parrot", "peach", "pen", "pencil", "penguin", "phone", "piano", "picture", "pig", "pizza", "plane", "plant", "plate", "plug", "pot", "pumpkin",
"queen", "quilt", "rabbit", "radio", "rain", "rainbow", "rat", "ring", "robot", "rocket",
"rope", "rug", "ruler", "sand", "school", "scissors", "shark", "sheep", "shirt", "shoe",
"shovel", "sink", "skate", "skirt", "sky", "snake", "snow", "sock", "spoon", "spider",
"sponge", "star", "stone", "straw", "sun", "table", "tiger", "toaster", "toilet", "tooth",
"torch", "towel", "train", "tree", "truck", "turtle", "umbrella", "vase", "violin", "volcano",
"watch", "water", "whale", "window", "wind", "wolf", "worm", "xylophone", "yarn", "zebra",
"actor", "arrow", "arm", "ankle", "alien", "ant", "anchor", "avocado", "arch", "anklet",
"axe", "armor", "apron", "aisle", "album", "attic", "anklet", "antenna", "ash", "art",
"apricot", "amplifier", "ambulance", "angel", "alarm", "arena", "arrowhead", "aisle", "ashtray", "anchor", "backpack", "badge", "balcony", "balloon", "barn", "barrel", "basket", "bat", "battery", "beacon",
"beetle", "bench", "binoculars", "blanket", "blender", "block", "blouse", "board", "boat", "bobcat",
"body", "bolt", "bone", "bonnet", "bookcase", "bookmark", "boot", "bottle", "bow", "bowl",
"boxer", "bracelet", "branch", "brick", "bridge", "broccoli", "broomstick", "brush", "bucket", "bug",
"bulb", "bull", "bunk", "bushel", "bush", "button", "cabinet", "cactus", "calculator", "camel",
"camp", "can", "candy", "canoe", "cap", "capsule", "caravan", "card", "carpet", "cart",
"castle", "caterpillar", "cave", "ceiling", "cell", "cello", "cement", "chain", "chalk", "champion",
"charger", "chart", "check", "cheetah", "cherry", "chess", "chest", "chimney", "chip", "chocolate",
"cicada", "circle", "clarinet", "claw", "cliff", "cloak", "clock", "closet", "cloud", "clown",
"club", "coal", "coat", "cobweb", "coin", "collar", "comb", "compass", "cone", "cork", "corn", "couch", "cough", "cowboy", "crab", "cracker", "crayon", "cream", "crib", "crocodile",
"crown", "cube", "cupcake", "curtain", "cushion", "dagger", "daisy", "dance", "dart", "deer",
"desk", "diamond", "diary", "dice", "dish", "disk", "diver", "dolphin", "donkey", "doorbell",
"doughnut", "dragon", "drain", "drill", "drone", "drumstick", "duckling", "dune", "dust", "easel",
"ear", "earth", "eel", "elbow", "engine", "envelope", "eraser", "escalator", "eyebrow", "fabric",
"fan", "farm", "feast", "fern", "ferry", "field", "fin", "fire", "fireman", "fishbowl",
"flagpole", "flame", "flashlight", "flood", "floorboard", "flute", "fly", "foam", "folder", "forest",
"forklift", "fountain", "foxglove", "frame", "freezer", "fridge", "frost", "fuel", "galaxy", "garage",
"garden", "garlic", "gate", "gazelle", "gem", "ghost", "giant", "giftbox", "ginger", "giraffe",
"glacier", "glasses", "glider", "globe", "glovebox", "gnome", "goose", "grapefruit", "grid", "grill", "guitarist", "gully", "gum", "gym", "hair", "hairbrush", "hairdryer", "hammerhead", "hamster", "hand",
"handle", "hanger", "harbor", "harmonica", "hatchet", "hay", "head", "headphones", "helmet", "heron",
"hilltop", "hippo", "hive", "hook", "hose", "hospital", "hotdog", "hourglass", "houseplant", "hurricane",
"iceberg", "icicle", "igloo", "illustration", "inchworm", "inkwell", "insect", "iron", "islander", "ivory",
"jacket", "jaguar", "jar", "javelin", "jelly", "jellyfish", "jet", "jewel", "joystick", "jug",
"jungle", "kangaroo", "kayak", "kettle", "keyboard", "kick", "kidney", "kitchen", "kite", "kitten",
"kiwi", "knee", "knife", "knight", "knot", "koala", "label", "ladle", "lake", "lamp",
"lantern", "laptop", "latch", "laundry", "lava", "lawn", "leaflet", "leash", "leg", "lemonade",
"lens", "lever", "library", "license", "lid", "lifeboat", "lightbulb", "lighthouse", "lightning", "lily",
"limb", "lime", "line", "lioness", "lip", "lizard", "log", "lollipop", "loofah", "luggage", "lunchbox", "magnet", "mailbox", "makeup", "mall", "mammoth", "map", "marker", "mask", "mattress",
"maze", "meadow", "meatball", "mechanic", "medicine", "melody", "menu", "mermaid", "microscope", "milkshake",
"mill", "minnow", "mirror", "mittens", "mole", "monastery", "monitor", "monster", "moonlight", "mosquito",
"motor", "motorcycle", "mountain", "mousepad", "muffin", "mushroom", "music", "musician", "nail", "napkin",
"necklace", "needle", "nest", "net", "newspaper", "night", "nightlight", "ninja", "noodle", "noose",
"notepad", "nugget", "nutcracker", "oak", "oar", "oasis", "oatmeal", "obelisk", "object", "octagon",
"octopus", "oil", "onion", "opera", "orangutan", "orchestra", "organ", "ostrich", "otter", "oven",
"owl", "oxygen", "paddle", "pail", "paint", "painter", "palace", "palm", "panda", "panel",
"panther", "pantyhose", "parachute", "parcel", "parrot", "passenger", "paste", "patch", "path", "peach",
"peacock", "peanut", "pear", "pebble", "pelican", "pen", "pencil", "penguin", "pepper", "perfume", "petal", "pickle", "picture", "pigeon", "pillar", "pillow", "pine", "pineapple", "pistol", "pitcher",
"pizza", "planet", "plastic", "plate", "playground", "pliers", "plow", "plug", "pocket", "podium",
"poem", "pointer", "police", "pony", "pool", "popcorn", "porcupine", "postcard", "poster", "potato",
"pouch", "puddle", "puffin", "pump", "puppet", "puzzle", "quail", "quart", "quartz", "queen",
"question", "quicksand", "quilt", "rabbit", "raccoon", "radar", "radio", "raft", "rag", "rail",
"railroad", "raincoat", "rake", "ramp", "ranger", "raspberry", "rat", "rattle", "raven", "razor",
"refrigerator", "remote", "rhinoceros", "ribbon", "rice", "ring", "river", "road", "robot", "rock",
"rocket", "roof", "room", "rooster", "rope", "rose", "rug", "ruler", "runway", "saddle",
"salad", "salt", "sandbox", "sandwich", "sapphire", "satellite", "saucepan", "sausage", "saw", "scale",
"scarf", "schoolbag", "scorpion", "screw", "sculpture", "seagull", "seal", "seesaw", "shadow", "shampoo", "shark", "shed", "shell", "shelter", "shield", "shirt", "shoe", "shop", "shovel", "shrimp",
"shrub", "shuttle", "sidewalk", "sign", "sink", "skateboard", "skeleton", "ski", "skirt", "skull",
"sky", "sled", "sleepingbag", "sleigh", "slime", "slingshot", "slipper", "slope", "slug", "smoke",
"snail", "snake", "sneeze", "snowball", "snowflake", "snowman", "soap", "sock", "sofa", "soldier",
"song", "soot", "spade", "spaghetti", "spark", "spatula", "speaker", "spear", "spectacles", "sphinx",
"spider", "spike", "spoon", "spot", "spring", "sprout", "square", "squirrel", "staircase", "stamp",
"star", "station", "statue", "steam", "steering", "stethoscope", "stick", "sticker", "stingray", "stocking",
"stomach", "stone", "stool", "stopwatch", "stove", "straw", "strawberry", "stream", "street", "string",
"submarine", "subway", "suit", "sun", "sunglasses", "sunlight", "sunset", "surfboard", "swan", "sweater",
"swing", "sword", "syrup", "tablecloth", "tablespoon", "tail", "tambourine", "tape", "tarp", "tattoo", "taxi", "teacup", "teapot", "teeth", "telephone", "telescope", "television", "tent", "thermometer", "thread",
"throne", "thumb", "thunder", "ticket", "tie", "tiger", "tile", "timer", "tissue", "toaster",
"toenail", "toilet", "tomato", "tongue", "toolbox", "toothbrush", "toothpaste", "tornado", "tortoise", "tower",
"toy", "tractor", "traffic", "train", "trampoline", "trash", "tray", "treasure", "tree", "triangle",
"trick", "trip", "trophy", "truck", "trumpet", "trunk", "tshirt", "tub", "tuba", "tulip",
"tunnel", "turkey", "turnip", "turtle", "tusk", "typewriter", "umbrella", "uncle", "underwear", "unicorn",
"utensil", "vacuum", "valley", "van", "vase", "vegetable", "velvet", "village", "vine", "violin",
"viper", "volcano", "vulture", "wagon", "waist", "waiter", "walkie", "wall", "wallet", "walnut",
"walrus", "wardrobe", "warrior", "watch", "water", "waterfall", "wave", "web", "wedding", "whale",
"wheel", "whisk", "whistle", "wig", "window", "windshield", "wing", "wire", "wizard", "wolf", "wombat", "wood", "woodpecker", "wool", "worm", "wrench", "wrist", "xylophone", "yacht", "yak",
"yarn", "yawn", "yeti", "yogurt", "yolk", "zebra", "zinc", "zipper", "zone", "zoo",
"accordion", "aisle", "antelope", "archer", "avalanche", "backhoe", "badger", "bagel", "balcony", "bandage",
"barber", "barricade", "basil", "beacon", "beetroot", "blizzard", "blueprint", "bobsled", "bonsai", "boulder",
"brace", "braces", "bride", "bronze", "bulldozer", "bunkbed", "burrito", "cabbage", "cabinet", "cactus",
"calculator", "canopy", "caramel", "caravan", "carousel", "cashew", "cassette", "caterpillar", "ceiling", "cellar",
"chalkboard", "chapstick", "checkers", "cherry", "chessboard", "chili", "chimney", "chisel", "clamp", "clipboard",
"clover", "cockroach", "coconut", "compass", "cone", "controller", "cookbook", "cork", "cowbell", "cracker",
"cranberry", "crate", "crib", "crouton", "cruise", "cucumber", "cupcake", "curtain", "cushion", "cutlery"
    ];
    return adjectives[Math.floor(Math.random() * adjectives.length)];

}

module.exports = getWord;